export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const EMPLOYEE_LOADED = 'EMPLOYEE_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_EMPLOYEE_SUCCESS = 'LOGIN_EMPLOYEE_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';


// Services
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_FAIL'
export const CREATE_SERVICE_FAIL = 'CREATE_SERVICE_FAIL'
export const GET_SERVICES = 'GET_SERVICES'
export const SERVICE_ERROR = 'SERVICE_ERROR'

// Misc
export const TOGGLE = 'TOGGLE'

